twitter:
  consumer_key: 'YOUR-CONSUMER-KEY'
  consumer_secret: 'YOUR-CONSUMER-SECRET'
  access_token_key: 'YOUR-ACCESS-TOKEN-KEY'
  access_token_secret: 'YOUR-ACCESS-TOKEN-SECRET'
elasticsearch:
  host: 'localhost:9200'
rabbitmq:
  host: 'localhost'